### ISSUE TITLE
Exception when biQuerySelect Returns Zero Rows

### ISSUE THREAD

**Issue by ps-githinjose** [samelamin/spark-bigquery#56]
I am getting the below exception when the bigquery select returns zero records

Exception in thread "main" java.lang.UnsupportedOperationException: empty collection
	at org.apache.spark.rdd.RDD$$anonfun$first$1.apply(RDD.scala:1370)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
	at org.apache.spark.rdd.RDD.first(RDD.scala:1367)
	at com.samelamin.spark.bigquery.BigQuerySQLContext.bigQuerySelect(BigQuerySQLContext.scala:92)

**Comment by samelamin** [comment]
sorry for the late reply I have been away

Yes that looks like a bug, feel free to send a pr in :)
