### ISSUE TITLE
Method saveAsBigQueryTable([class java.lang.String]) does not exist: Issue persists even after shading guava dependecies

### ISSUE THREAD

**Issue by dduran28** [samelamin/spark-bigquery#83]
I am still experiencing the above issue when trying to run the PySpark example in Databricks. 

`bq = bigquery.BigQuerySQLContext(session._wrapped._jsqlContext)
bq.setGcpJsonKeyFile(KEY_FILE)
bq.setBigQueryProjectId(BQ_PROJECT_ID)
bq.setGSProjectId(BQ_PROJECT_ID)
bq.setBigQueryGcsBucket(STAGING_BUCKET)
bq.setBigQueryDatasetLocation(DATASET_LOCATION)

bqDF = bigquery.BigQueryDataFrame(df._jdf)
bqDF.saveAsBigQueryTable(
    "{0}:{1}.{2}".format(BQ_PROJECT_ID, DATASET_ID, TABLE_NAME)`

gives me the following error

> Py4JError: An error occurred while calling o333.saveAsBigQueryTable. Trace:
py4j.Py4JException: Method saveAsBigQueryTable([class java.lang.String]) does not exist
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:341)
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:349)
	at py4j.Gateway.invoke(Gateway.java:286)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)>

This is my cluster configuration:
![image](https://user-images.githubusercontent.com/45972558/79149539-53568680-7d95-11ea-8083-c9b9e1104c11.png)

These are my installed JARs and libraries 
![image](https://user-images.githubusercontent.com/45972558/79149456-315d0400-7d95-11ea-89f9-b1e50ce51dc0.png)

**Comment by dduran28** [comment]
Bump

**Comment by samelamin** [comment]
Is this still an issue?

**Comment by dduran28** [comment]
Yes it is

**Comment by samelamin** [comment]
this is dependant on your cluster, can you let me know where you are running it? 

spark version, manually create cluster vs EMR/Databricks/Dataproc
